name: Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: setup nodejs
      uses: actions/setup-node@v5
      with:
        node-version: 22

    - name: Checkout
      uses: actions/checkout@v5

    - name: Cache Dependency
      uses: actions/cache@v5
      id: cache_dependency
      env:
        cache-name: cache-dependency
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('app/yarn.lock') }}

    - name: Install Dependency
      if: ${{ steps.cache_dependency.outputs.cache-hit != 'true' }}
      run: |
        cd app
        yarn --frozen-lockfile
        yarn build
        ls dist

    - uses: actions/upload-artifact@v6
      with:
        name: app
        compression-level: 0
        path: app/dist/app-1.0.0-ia32-win.zip